#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Jul 18, 2020 07:21:09 PM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    image263 "./logo.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans Mono} -size 14"
set vTcl(actual_gui_font_dft_desc) $desc
set vTcl(actual_gui_font_dft_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 14"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {DejaVu Sans Mono} -size 14"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 12"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 12"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 500x300+547+229
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1345 668
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "OSINT Project"
    vTcl:DefineAlias "$top" "main" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 300 -highlightcolor black -width 195 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "main" 1
    set site_3_0 $top.fra46
    button $site_3_0.but47 \
        -activebackground #f9f9f9 -activeforeground black -background #36bcff \
        -command raiseTwitter -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 3m \
        -state active -text Twitter 
    vTcl:DefineAlias "$site_3_0.but47" "twitter_Btn" vTcl:WidgetProc "main" 1
    button $site_3_0.but48 \
        -activebackground #f9f9f9 -activeforeground black -background #40ff73 \
        -command raiseAnalyze -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Analyze Data} -width 200 
    vTcl:DefineAlias "$site_3_0.but48" "analyze_Btn" vTcl:WidgetProc "main" 1
    button $site_3_0.but49 \
        -activebackground #f9f9f9 -activeforeground black -background #631818 \
        -command checkExit -disabledforeground #70101d -font TkDefaultFont \
        -foreground #ffffff -highlightcolor black -text Quit 
    vTcl:DefineAlias "$site_3_0.but49" "quitBut" vTcl:WidgetProc "main" 1
    button $site_3_0.but50 \
        -activebackground #f9f9f9 -activeforeground black -background #ff2448 \
        -command raiseYoutube -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -state active \
        -text Youtube 
    vTcl:DefineAlias "$site_3_0.but50" "youtube_Btn" vTcl:WidgetProc "main" 1
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -y 0 -rely 0.083 -width 200 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -y 0 -rely 0.417 -width 200 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -y 0 -rely 0.75 -width 200 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -y 0 -rely 0.25 -width 200 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra51 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra51" "Twitter" vTcl:WidgetProc "main" 1
    set site_3_0 $top.fra51
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Search Term: } 
    vTcl:DefineAlias "$site_3_0.lab52" "Label1" vTcl:WidgetProc "main" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Location: } 
    vTcl:DefineAlias "$site_3_0.lab54" "Label1_1" vTcl:WidgetProc "main" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Start Date: } 
    vTcl:DefineAlias "$site_3_0.lab55" "Label1_2" vTcl:WidgetProc "main" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Radius: 
    vTcl:DefineAlias "$site_3_0.lab56" "Label2" vTcl:WidgetProc "main" 1
    label $site_3_0.lab58 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Max Tweets: } 
    vTcl:DefineAlias "$site_3_0.lab58" "Label1_3" vTcl:WidgetProc "main" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text {End: } 
    vTcl:DefineAlias "$site_3_0.lab59" "Label1_1" vTcl:WidgetProc "main" 1
    button $site_3_0.but60 \
        -activebackground #f9f9f9 -activeforeground black -background #0fba0f \
        -command collectTwitter -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 1 \
        -pady 3 -text Collect 
    vTcl:DefineAlias "$site_3_0.but60" "collectTwitter" vTcl:WidgetProc "main" 1
    entry $site_3_0.ent61 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable twitter_query -width 10 
    vTcl:DefineAlias "$site_3_0.ent61" "twitter_query" vTcl:WidgetProc "main" 1
    entry $site_3_0.ent63 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable twitter_end_date -width 10 
    vTcl:DefineAlias "$site_3_0.ent63" "twitter_end_date" vTcl:WidgetProc "main" 1
    entry $site_3_0.ent64 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable twitter_max_tweets -width 10 
    vTcl:DefineAlias "$site_3_0.ent64" "twitter_max_tweets" vTcl:WidgetProc "main" 1
    entry $site_3_0.ent65 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable twitter_radius -width 10 
    vTcl:DefineAlias "$site_3_0.ent65" "twitter_radius" vTcl:WidgetProc "main" 1
    entry $site_3_0.ent66 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable twitter_location -width 10 
    vTcl:DefineAlias "$site_3_0.ent66" "twitter_location" vTcl:WidgetProc "main" 1
    entry $site_3_0.ent67 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable twitter_start_date -width 10 
    vTcl:DefineAlias "$site_3_0.ent67" "twitter_start_date" vTcl:WidgetProc "main" 1
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.1 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.417 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.233 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.5 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.617 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.3 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.75 -width 260 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.1 -width 150 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.3 -width 150 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent64 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.617 -width 150 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.5 -width 150 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.417 -width 150 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent67 \
        -in $site_3_0 -x 0 -relx 0.4 -y 0 -rely 0.217 -width 150 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra74 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.fra74" "Youtube" vTcl:WidgetProc "main" 1
    set site_3_0 $top.fra74
    button $site_3_0.but75 \
        -activebackground #f9f9f9 -activeforeground black -background #0fba0f \
        -command collectYoutube -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Collect Data} 
    vTcl:DefineAlias "$site_3_0.but75" "collectYoutube" vTcl:WidgetProc "main" 1
    label $site_3_0.lab77 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Keyword 
    vTcl:DefineAlias "$site_3_0.lab77" "youtube_keyword" vTcl:WidgetProc "main" 1
    entry $site_3_0.ent78 \
        -background white -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable youtube_keyword -width 10 
    vTcl:DefineAlias "$site_3_0.ent78" "youtube_query" vTcl:WidgetProc "main" 1
    entry $site_3_0.ent45 \
        -background white -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable youtube_keyword -width 10 
    vTcl:DefineAlias "$site_3_0.ent45" "youtube_count" vTcl:WidgetProc "main" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Count 
    vTcl:DefineAlias "$site_3_0.lab47" "youtube_count_Label" vTcl:WidgetProc "main" 1
    place $site_3_0.but75 \
        -in $site_3_0 -x 0 -relx 0.067 -y 0 -rely 0.75 -width 260 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 0 -relx 0.333 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.09 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent78 \
        -in $site_3_0 -x 0 -relx 0.2 -y 0 -rely 0.267 -width 180 -relwidth 0 \
        -height 29 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent45 \
        -in $site_3_0 -x 0 -relx 0.2 -y 0 -rely 0.533 -width 180 -relwidth 0 \
        -height 29 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.333 -y 0 -rely 0.4 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.09 -anchor nw \
        -bordermode ignore 
    frame $top.fra79 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 295 -highlightcolor black -width 295 
    vTcl:DefineAlias "$top.fra79" "Logo" vTcl:WidgetProc "main" 1
    set site_3_0 $top.fra79
    label $site_3_0.lab83 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image image263 
    vTcl:DefineAlias "$site_3_0.lab83" "logo" vTcl:WidgetProc "main" 1
    place $site_3_0.lab83 \
        -in $site_3_0 -x 0 -relx 0.033 -y 0 -rely 0.833 -width 0 -relwidth 1 \
        -height 0 -relheight 1 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 0.4 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    place $top.fra51 \
        -in $top -x 0 -relx 0.4 -y 0 -width 0 -relwidth 0.6 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    place $top.fra74 \
        -in $top -x 0 -relx 0.4 -y 0 -width 0 -relwidth 0.6 -height 0 \
        -relheight 1 -anchor nw -bordermode ignore 
    place $top.fra79 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.733 -width 0 -relwidth 0.6 \
        -height 0 -relheight 1 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

