#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Jul 27, 2020 09:44:13 PM CDT  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Login (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def destroy_Login():
    global w
    w.destroy()
    w = None

class Login:
    def __init__(self, top=None):
        self.destroy_Login=destroy_Login
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("311x186+650+150")
        top.minsize(1, 1)
        top.maxsize(1345, 672)
        top.resizable(1, 1)
        top.title("Login")

        self.userName = tk.Entry(top)
        self.userName.place(relx=0.257, rely=0.269,height=23, relwidth=0.498)
        self.userName.configure(background="white")
        self.userName.configure(font="TkFixedFont")

        self.userName_Label = tk.Label(top)
        self.userName_Label.place(relx=0.257, rely=0.108, height=23, width=156)
        self.userName_Label.configure(cursor="fleur")
        self.userName_Label.configure(text='''UserName:''')

        self.password = tk.Entry(top)
        self.password.place(relx=0.257, rely=0.591,height=23, relwidth=0.498)
        self.password.configure(background="white")
        self.password.configure(font="TkFixedFont")

        self.password_Label = tk.Label(top)
        self.password_Label.place(relx=0.257, rely=0.43, height=23, width=155)
        self.password_Label.configure(text='''Password:''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.257, rely=0.78, height=31, width=155)
        self.Button1.configure(background="#47d85b")
        self.Button1.configure(command=lambda :login_support.login(self.userName.get(),self.password.get()))
        self.Button1.configure(text='''Login''')
        self.userName.insert(tk.END, "root")
        self.password.insert(tk.END,"password")

if __name__ == '__main__':
    vp_start_gui()


